require(car)
require(MASS)
seedset=read.csv(file="seedsetdata.csv", h=T)
GHQ <- glmer(seed_set ~Treatment + (1 |clone), data = seedset, family = poisson(link = "log"), nAGQ = 2)
summary(GHQ)
predictedscores=predict(GHQ,re.form=NA, type="response")
table(predictedscores)
confint(GHQ)
summary(GHQ)
##How to visualize

###Seed weight
qqp(seedset$ave_seed_weight, "norm")
qqp(seedset$ave_seed_weight, "lnorm")
nbinom <- fitdistr(seedset$ave_seed_weight, "Negative Binomial")
qqp(seedset$ave_seed_weight, "nbinom", size = nbinom$estimate[[1]], mu = nbinom$estimate[[2]])
poisson <- fitdistr(seedset$ave_seed_weight, "Poisson")
qqp(seedset$ave_seed_weight, "pois", poisson$estimate)
gamma <- fitdistr(seedset$ave_seed_weight, "gamma")
qqp(seedset$ave_seed_weight, "gamma", shape = gamma$estimate[[1]], rate = gamma$estimate[[2]])
###model(normal distrubution is most acurate)
library(nlme)
model4.1fit<-lme(ave_seed_weight~Treatment, random=~1|clone, seedset, method= "REML")
summary(model4.1fit)
anova(model4.1fit)
random.effects(model4.1fit)
#structure for Random Effect
model4.1Afit<-gls(ave_seed_weight~Treatment, data=seedset)
anova(model4.1fit,model4.1Afit)
.8015/2
## random effect is not significant, therefore we can eliminate it??
linearweight<-lm(ave_seed_weight~Treatment, data=seedset)
summary(linearweight)
boxplot(ave_seed_weight~clone, data=seedset)
predictedscores2=predict(linearweight,re.form=NA, type="response")
table(predictedscores2)
citation()
system.file(package="lme4") 
citation("lme4")
citation("car")
citation("stats")

mean(subset(seedset, Treatment == "outcrossed")$seed_set)
mean(subset(seedset, Treatment == "selfed")$seed_set)
(subset(seedset, Treatment == "outcrossed")$seed_set)
install.packages("plotrix")
library(plotrix)
std.error(subset(seedset, Treatment == "outcrossed")$seed_set)
std.error(subset(seedset, Treatment == "selfed")$seed_set)

mean(subset(seedset, Treatment == "outcrossed")$ave_seed_weight)
mean(subset(seedset, Treatment == "selfed")$ave_seed_weight)
std.error(subset(seedset, Treatment == "outcrossed")$ave_seed_weight)
std.error(subset(seedset, Treatment == "selfed")$ave_seed_weight)

install.packages("pastecs")
library(pastecs)
stat.desc(seedset) 

